<?php
/**
 * Product view template
 *
 * @see \Boxalino\Intelligence\Block\SearchMessage
 */
?>

<?php
echo $this->test();
  if ($this->isActive()) {
    if (!empty($this->getSearchMessageTitle())) {
      echo "<style>.page-title-wrapper{display: none !important;}</style>"; //if there is a searchmessage, hide the page title
    }

    switch ($this->getSearchMessageDisplayType()) {
      case 'main-image': ?>
        <div class="bx-main-image-search-message">
          <span>
            <strong class="bx-main-image-search-message-title <?php echo $this->getSearchMessageTitleCssClass(); ?>"><?php echo $this->getSearchMessageTitle(); ?></strong>
          </span>
          <span class="bx-main-image-search-message-main-image <?php echo $this->getSearchMessageMainImageCssClass();?>">
            <img src="<?php echo $this->getSearchMessageMainImage(); ?>"/>
          </span>
        </div>
      <?php break;

      case 'main-image-link':?>
        <div class="bx-main-image-link-search-message <?php echo $response->getSearchMessageLinkCssClass(); ?>">
          <a href="<?php echo $response->getSearchMessageLink();?>" class="bx-main-image-link-search-message-link <?php echo $response->getSearchMessageMainLinkCssClass();?>">
            <span>
              <strong class="bx-main-image-link-search-message-title <?php echo $response->getSearchMessageTitleCssClass();?>"><?php echo $response->getSearchMessageTitle(); ?></strong>
            </span>
            <span class="bx-main-image-link-search-message-main-image <?php echo $response->getSearchMessageMainImageCssClass();?>">
              <img src="<?php echo $response->getSearchMessageMainImage(); ?>"/>
            </span>
          </a>
        </div>
      <?php break;

      case 'side-image':?>
        <div class="bx-side-image-search-message">
          <div class="bx-side-image-search-message-container-left">
            <p class="bx-side-image-search-message-title <?php echo $response->getSearchMessageTitleCssClass(); ?>">>
              <?php echo $response->getSearchMessageTitle(); ?>
            </p>
            <p class="info bx-side-image-search-message-description <?php echo $response->getSearchMessageDescriptionCssClass();?>">
              <?php echo $response->getSearchMessageDescription(); ?>
            </p>
            </div>
            <div class="bx-side-image-search-message-container-right">
              <div class="bx-side-image-search-message-side-image<?php echo $response->getSearchMessageSideImageCssClass(); ?>">
                <img src="<?php echo $response->getSearchMessageSideImage(); ?>"/>
              </div>
          </div>
        </div>
      <?php break;

      case 'side-image-link': ?>
        <div class="bx-side-image-link-search-message">
          <div class="bx-side-image-link-search-message-container-left">
            <p class="bx-side-image-link-search-message-title<?php echo $response->getSearchMessageTitleCssClass(); ?>">
              <?php echo $response->getSearchMessageTitle(); ?>
            </p>
          <a href="<?php echo $response->getSearchMessageLink(); ?>" class="bx-side-image-link-search-message-link"<?php echo $response->getSearchMessageLinkCssClass(); ?>">
            <p class="info bx-ide-image-link-search-message-description <?php $response->getSearchMessageDescriptionCssClass();?>">
                <?php echo $response->getSearchMessageDescription(); ?>
            </p>
          </a>
          </div>
          <div class="bx-side-image-link-search-message-container-right">
            <div class="bx-side-image-link-search-message-side-image<?php echo $response->getSearchMessageSideImageCssClass(); ?>">
              <img src="<?php echo $response->getSearchMessageSideImage(); ?>"/>
            </div>
          </div>
        </div>
      <?php break;

      case 'no-image': ?>
        <div class="bx-no-image-search-message">
          <p class="bx-no-image-search-message-title<?php echo $response->getSearchMessageTitleCssClass(); ?>">
            <?php echo $response->getSearchMessageTitle(); ?>
          </p>
          <p class="info bx-no-image-search-message-description <?php $response->getSearchMessageDescriptionCssClass();?>">
            <?php echo $response->getSearchMessageDescription(); ?>
          </p>
        </div>
      <?php break;

      case 'no-image-link': ?>
        <div class="bx-no-image-link-search-message">
          <p class="bx-no-image-link-search-message-title<?php echo $response->getSearchMessageTitleCssClass(); ?>">
            <?php echo $response->getSearchMessageTitle(); ?>
          </p>
          <a href="<?php echo $response->getSearchMessageLink(); ?>" class="bx-no-image-link-search-message-link <?php echo $response->getSearchMessageLinkCssClass(); ?>">
            <p class="info bx-no-image-link-search-message-description <?php $response->getSearchMessageDescriptionCssClass();?>">
              <?php echo $response->getSearchMessageDescription(); ?>
            </p>
          </a>
        </div>
      <?php break;

      default:
      # code...
      break;
    }
  }
?>
